### ISSUE TITLE
[Support] How to change style of editor ?

### ISSUE THREAD

**Issue by rishab-sharma** [guilhermelimak/react-codejar#15]
Hi, I am new to react, can please help me with how to apply different styles and enable line numbers like code-jar.

Also how to switch between languages?

**Comment by guilhermelimak** [comment]
Hey Rishab,

About the styles, which ones would you want to change exactly? If it is the syntax highlighter colors they should be changed on the highlight function you pass as a prop (probably using PrismJS or something similar).

Right now I don't think line numbers are really supported here, I'll take a quick look to see what can be done since that's a nice (and kind of important) feature to have.

To switch between languages you will have to change your highlight function. Are you using PrismJS? If so you can take a look at their docs to see how to change the language there. Here is a list of the supported languages by PrimsJS https://prismjs.com/#supported-languages, you can also read the rest of the docs there too.

**Comment by guilhermelimak** [comment]
@rishab-sharma  Hey, just added the line numbers support, now you can pass the lineNumbers prop and it should work just fine.

**Comment by rishab-sharma** [comment]
Thank you so much @guilhermelimak for such a quick response and the feature addition.
